<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/12/26 0026
 * Time: 10:24
 */

namespace app\controllers;


use app\m\Uploader;
use Yii;
use yii\helpers\Url;
use yii\web\UploadedFile;

class VideoController extends  ComBaseController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->enableCsrfValidation =false;
    }


    function actionUploadpic(){


        $result = new \stdClass();
        $result->name = '';
        $result->status = 0;
        $result->url = "";
        $model = new Uploader();




        if (Yii::$app->request->isPost) {

            $model->imageFile = UploadedFile::getInstance($model, 'file');


            $getUploadResult = $model->upload();

            if ($getUploadResult) {
                // 文件上传成功
                $result->name = $getUploadResult;

                $result->url =  Url::to('@web/images/videos/'.$getUploadResult.".".$model->imageFile->extension, 'http');//真实图片的访问地址
                $result->status = 1;
            }
        }



        return json_encode($result);
    }
}