<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/12/26 0026
 * Time: 10:24
 */

namespace app\controllers;


use app\m\ModelFactory;
use app\m\Uploader;
use Qiniu\QiniuUtil;
use Yii;
use yii\helpers\Url;
use yii\web\UploadedFile;

class VideoController extends  ComBaseController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->enableCsrfValidation =false;
    }


    function actionImgcallback() //图片上传回调
    {

        //七牛Post我们这个地址了
        if(Yii::$app->request->isPost)
        {

            $model=ModelFactory::loadModel("videos_img");//取出图片表model
            $vi=$model::find()->where(["img_name"=>Yii::$app->request->post("key")])->one();
            if($vi)
            {
                $vi->isuploaded=1;
                $vi->save();

                $result=new \stdClass();
                $result->response="success";
                Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;  //设置当前 content-type为application/json
                return  $result;
            }

        }

    }




    function actionUptoken(){ //返回uptoken
        $userid = 0; //默认0 超级管理员
        $util = new QiniuUtil();
        $ret = $util->getUploadToken($userid);

        return json_encode($ret);
    }


    function actionUploadpic(){


        $result = new \stdClass();
        $result->name = '';
        $result->status = 0;
        $result->url = "";
        $model = new Uploader();




        if (Yii::$app->request->isPost) {

            $model->imageFile = UploadedFile::getInstance($model, 'file');


          return $model->upload();


        }



        return "";
    }
}